### ISSUE TITLE
python CIK from ticker

### ISSUE THREAD

**Issue by lgibson212** [mr-z-ro/msf-401k-hackathon-tools#1]
``` python
import re
from cPickle import dump
from requests import get

DEFAULT_TICKERS = ['goog', 'aapl']
URL = 'http://www.sec.gov/cgi-bin/browse-edgar?CIK={}&Find=Search&owner=exclude&action=getcompany'
CIK_RE = re.compile(r'.*CIK=(\d{10}).*')

cik_dict = {}
for ticker in DEFAULT_TICKERS:
    results = CIK_RE.findall(get(URL.format(ticker)).content)
    if len(results):
        cik_dict[str(ticker).lower()] = str(results[0])
f = open('cik_dict', 'w')
dump(cik_dict, f)
f.close()
```

**Comment by ghost** [comment]
Check it out, @lgibson212 ! 

https://github.com/mr-z-ro/msf-401k-hackathon-tools/commit/3ddb3f1e57385bc88e052d19731697de3dc5093a

Will add to json, mysql dump, and live db shortly.

**Comment by ghost** [comment]
json, mysql dump, and live db have all been updated as well.

i realize it's not the best normalization of the data, but at least it exists now! thanks for the awesome find/contribution! :)
